server:
  port: 8088

spring:
  kafka:
      bootstrapServer: 192.168.123.127:9092,192.168.123.127:9093
      groupId: qj-kafka
      topic:
          orderTopic: qj-order
          tradeTopic: qj-trade